### ISSUE TITLE
node.source property is overwriting by node-falafel node.source() function

### ISSUE THREAD

**Issue by sanex3339** [substack/node-falafel#63] opened 2017-05-18 16:35 UTC
Hi, i found the problem - `node.source` property is overwriting by `falafel` `node.source()` function.

For example following AST
http://esprima.org/demo/parse.html?code=import%20Foo%20from%20'bar'%3B%0A

`ImportDeclaration` has `source` property that will overwrite by `falafel`

Line with problem:
https://github.com/substack/node-falafel/blob/6f5cbc344cfd512b099e1144334ba3ffc51115a9/index.js#L58

**Comment by golyshevd** [comment] 2017-08-10 13:20
Hi! I want to recognize specific import declarations by node[type=ImportDeclaration].source, but i cant because of node.source is overriden by falafel. Need manually parse(node.souce())?

Also: original `node[type=ImportDeclaration].source` which is `Literal` is not linked with parent ImportDeclaration node and falafel is not traversed over that

**Comment by Loilo** [comment] 2019-04-30 06:37
For future readers: I needed this fixed, so I started out on a package that resembles falafel's API but doesn't have most of its issues.

If you're interested, take a look at [Yufka](https://www.npmjs.com/package/yufka).

**Comment by goto-bus-stop** [comment] 2020-03-09 20:35
Thanks for the report, closing as duplicate of #45.

**Closed by goto-bus-stop** 2020-03-09 20:35 UTC
